# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.provider "parallels"
  
  config.vm.provider "parallels" do |v|
    v.name = "Stockr"
  end
  
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "parallels/ubuntu-14.04"

  # MICHAEL: This is to link the shared folder for the key
  config.vm.synced_folder "../", "/var/stockr"

  # MICHAEL: This is the path for the provisioning file
  config.vm.provision "shell", path: "./provision.sh"

end
